# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AstolfoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainUI(object):
    def setupUi(self, mainUI):
        mainUI.setObjectName("mainUI")
        mainUI.resize(720, 720)
        mainUI.setMinimumSize(QtCore.QSize(495, 418))
        mainUI.setMaximumSize(QtCore.QSize(1024, 768))
        mainUI.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textEdit = QtWidgets.QLineEdit(mainUI)
        self.textEdit.setGeometry(QtCore.QRect(10, 670, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color:rgb(255, 255, 255)")
        self.textEdit.setObjectName("textEdit")
        self.OutputWindow = QtWidgets.QTextBrowser(mainUI)
        self.OutputWindow.setGeometry(QtCore.QRect(10, 490, 701, 151))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(11)
        self.OutputWindow.setFont(font)
        self.OutputWindow.setStyleSheet("color:rgb(255, 255, 255)")
        self.OutputWindow.setObjectName("OutputWindow")
        self.SendButton = QtWidgets.QPushButton(mainUI)
        self.SendButton.setGeometry(QtCore.QRect(540, 660, 80, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setUnderline(False)
        self.SendButton.setFont(font)
        self.SendButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.SendButton.setObjectName("SendButton")
        self.ProgressLabel = QtWidgets.QLabel(mainUI)
        self.ProgressLabel.setGeometry(QtCore.QRect(20, 440, 691, 31))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setPointSize(15)
        self.ProgressLabel.setFont(font)
        self.ProgressLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ProgressLabel.setStyleSheet("color: rgb(255, 255, 255)")
        self.ProgressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressLabel.setObjectName("ProgressLabel")
        self.AISpeaking = QtWidgets.QLabel(mainUI)
        self.AISpeaking.setGeometry(QtCore.QRect(250, 100, 201, 201))
        self.AISpeaking.setText("")
        self.AISpeaking.setPixmap(QtGui.QPixmap("UI/gif2.gif"))
        self.AISpeaking.setObjectName("AISpeaking")
        self.SpeakButton = QtWidgets.QPushButton(mainUI)
        self.SpeakButton.setGeometry(QtCore.QRect(640, 660, 80, 41))
        font = QtGui.QFont()
        font.setFamily("Moon")
        font.setUnderline(False)
        self.SpeakButton.setFont(font)
        self.SpeakButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.SpeakButton.setObjectName("SpeakButton")

        self.retranslateUi(mainUI)
        QtCore.QMetaObject.connectSlotsByName(mainUI)

    def retranslateUi(self, mainUI):
        _translate = QtCore.QCoreApplication.translate
        mainUI.setWindowTitle(_translate("mainUI", "Astolfo (by Sai Ram and Hari Krishna)"))
        self.textEdit.setPlaceholderText(_translate("mainUI", "Input here ...."))
        self.OutputWindow.setPlaceholderText(_translate("mainUI", "Output here ..."))
        self.SendButton.setText(_translate("mainUI", "Send"))
        self.ProgressLabel.setText(_translate("mainUI", "Waiting for command ... "))
        self.SpeakButton.setText(_translate("mainUI", "Speak"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainUI = QtWidgets.QWidget()
    ui = Ui_mainUI()
    ui.setupUi(mainUI)
    mainUI.show()
    sys.exit(app.exec_())
